name: Test CI
on:
  pull_request:
  push:
    branches:
      - '!main'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js v20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm v9.x
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install deps
        run: pnpm install

      - name: Test query-string
        working-directory: packages/query-string
        run: npm run test:cov

      - name: Upload coverage of query-string to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: umdjs/query-string
          flags: query-string
          directory: ./packages/query-string/coverage/
